#[cfg(feature = "crp")]
pub mod cropping;
#[cfg(feature = "det")]
pub mod detecting;
#[cfg(feature = "gen")]
pub mod generating;
pub(crate) mod helpers;
pub(crate) mod rect;
pub(crate) mod transforms;
